DEWAS/urls.py
from django.conf.urls import patterns, include, url
from Auctioneer.views import *
from Auctioneer.rest_views import *
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DEWAS.views.home', name='home'),
    # url(r'^DEWAS/', include('DEWAS.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # Main UI
    url(r'^auctioneer/?$', home),
    url(r'^auctioneer/home/?$', home),
    url(r'^auctioneer/auctions/?$', browse),
    url(r'^auctioneer/signup/?$', sign_up),
    url(r'^auctioneer/account/?$', account),
    url(r'^auctioneer/account/auctions/?$', auctions),
    url(r'^auctioneer/login/?$', auth),
    url(r'^auctioneer/logout/$', leave),
    url(r'^auctioneer/auctions/(?P<auction_id>\d+)/?$', details),
    url(r'^auctioneer/auctions/create/?$', create),
    url(r'^auctioneer/auctions/confirm/?$', confirm),
    url(r'^auctioneer/auctions/(?P<auction_id>\d+)/edit/?$', edit),
    url(r'^auctioneer/auctions/(?P<auction_id>\d+)/ban/?$', ban),
    url(r'^auctioneer/language/?$', language),
    url(r'^auctioneer/auctions/(?P<auction_id>\d+)/bid/?$', bid),

    # RESTful interface
    url(r'^auctioneer/api/auctions/(?P<query>\w+)?/?$', rest_auctions),
    url(r'^auctioneer/api/auctions/(?P<auction_id>\d+)/bid/?$', rest_bids)

)

Auctioneer/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User
from decimal import Decimal
from datetime import datetime

# Create your models here.


class Auctions(models.Model):

    seller = models.ForeignKey(User)
    title = models.CharField(null=False, max_length=30)
    description = models.TextField(max_length=150)
    version = models.PositiveIntegerField(default=0)
    startingPrice = models.DecimalField(default=0.00, max_digits=12, decimal_places=2,
                                        validators=[MinValueValidator(Decimal('0.00'))])
    startDate = models.DateTimeField(null=False)
    stopDate = models.DateTimeField(null=False)
    banned = models.BooleanField(default=False)
    resolved = models.BooleanField(default=False)

    class Meta:
        permissions = (('ban_auctions', 'Can ban auctions'),)
        ordering = ['startDate']
        #order_with_respect_to = 'startDate'

    @classmethod
    def get_nearest(cls):
        try:
            return cls.objects.filter(banned=False, resolved=False, stopDate__gt=datetime.now()).order_by('stopDate')[:3]
        except:
            try:
                return cls.get_all()
            except:
                return None

    @classmethod
    def get_by_seller(cls, seller):
        try:
            return cls.objects.filter(seller=seller)
        except:
            return None

    @classmethod
    def get_by_id(cls, auction_id):
        try:
            return cls.objects.get(id=auction_id)
        except:
            return None

    @classmethod
    def get_by_query(cls, query):
        query = query.replace('\\', '\\\\')
        try:
            return cls.objects.filter(title__iregex=query, banned=False)
        except:
            return None

    @classmethod
    def get_all(cls):
        try:
            return cls.objects.all()
        except:
            return None

    @classmethod
    def get_active(cls):
        try:
            return cls.objects.filter(resolved=False, banned=False)
        except:
            return None


class Bids(models.Model):

    auction = models.ForeignKey(Auctions)
    bidder = models.ForeignKey(User)
    amount = models.DecimalField(max_digits=12, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    timestamp = models.DateTimeField()

    class Meta:
        ordering = ['-amount']
        #order_with_respect_to = 'auction'

    @classmethod
    def get_by_auction_all(cls, auction):
        try:
            return cls.objects.filter(auction=auction)
        except:
            return None

    @classmethod
    def get_by_auction_highest(cls, auction):
        try:
            return cls.objects.filter(auction=auction)[1]
        except:
            return None


class Languages(models.Model):

    user = models.ForeignKey(User, primary_key=True)
    language = models.CharField(max_length=10, default='en')

    @classmethod
    def get_language_by_user(cls, user):
        try:
            return cls.objects.get(user=user)
        except:
            return None

templates/account.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 //EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>

	<head>

		<title>Auctioneer - {{ title }}</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link href="{% static "style_main.css"%}" rel="stylesheet" type="text/css">

	</head>

	<body>

		<div id=Container>

			<div id=PrimaryMenu>
				<h1>Auctioneer - {{ title }}</h1>
			</div>

            {% include "links.html" %}

			<div id=TopPatch>
				<!-- Patch element at top of the page -->
			</div>

			<div id=Content>

                <div>
                    <h3>{% trans "Account details for:" %} {{ user.username }}</h3>
                    <form action="/auctioneer/account/" method="post">
                        {% csrf_token %}

                        <label>
                            <span>{% trans "E-Mail:" %}</span>
                            <input class="field" type="text" size="30" name="email" value="{{ user.email }}">
                        </label>
                        <label>
                            <span>{% trans "Password:" %}</span>
                            <input class="field" type="password" size="30" name="password">
                        </label>
                        <br>
                        <label>
                            <input class="button" type="submit" size="30" value={% trans "Save" %}>
                        </label>
                    </form>
                </div>

			</div>

		</div>

	</body>

</html>

templates/auth.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 //EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>

	<head>

		<title>Auctioneer - {{ title }}</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link href="{% static "style_main.css"%}" rel="stylesheet" type="text/css">

	</head>

	<body>

		<div id=Container>

			<div id=PrimaryMenu>
				<h1>Auctioneer - {{ title }}</h1>
			</div>

            {% include "links.html" %}

			<div id=TopPatch>
				<!-- Patch element at top of the page -->
			</div>

			<div id=Content>

                <div>
                    <form action="/auctioneer/login/" method="post">
                        {% csrf_token %}
                        <label>
                            <span>{% trans "Username:" %}</span>
                            <input type="text" size="30" name="username">
                        </label>
                        <label>
                            <span>{% trans "Password" %}</span>
                            <input type="password" size="30" name="password">
                        </label>
                        <input type="hidden" name="next" value="{{ next }}"
                        <br>
                        <label>
                            <input class="button" type="submit" size="30" value={% trans "Login" %}>
                        </label>
                    </form>
                </div>

			</div>

		</div>

	</body>

</html>

templates/bid.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 //EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>

	<head>

		<title>Auctioneer - {{ title }}</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link href="{% static "style_main.css"%}" rel="stylesheet" type="text/css">

	</head>

	<body>

		<div id=Container>

			<div id=PrimaryMenu>
				<h1>Auctioneer - {{ title }}</h1>
			</div>

            {% include "links.html" %}

			<div id=TopPatch>
				<!-- Patch element at top of the page -->
			</div>

			<div id=Content>

                <div>
                    <h3>{{ auction.title }}{% if auction.banned %} [BANNED]{% endif %}</h3>
                    <p>{% trans "Created by:" %} {{ auction.seller }}</p>
                    <p>{% trans "Deadline:" %} {{ auction.stopDate }}</p>
                    <p>{% trans "Description:" %} {{ auction.description }}</p>
                    {% with auction.bids_set.all|first as top %}
                    {% if top %}
                    <h3>{% trans "Current price:" %} {{ top.amount }} EUR</h3>
                    <p>{% trans "by:" %} {{ top.bidder }}</p>
                    <p>@ {{ top.timestamp }}</p>
                    {% else %}
                    <h3>{% trans "Current price:" %} {{ auction.startingPrice }} EUR</h3>
                    {% endif %}
                    {% endwith %}
                </div>

                {% if message %}
                <div>
                    <h3>{{ message }}</h3>
                </div>
                {% endif %}

                <div>
                    <h3>{% trans "Your bid" %}</h3>
                    <form action="/auctioneer/auctions/{{ auction.id }}/bid/" method="post">
                        {% csrf_token %}
                        <label>
                            <span>{% trans "Amount" %}</span>
                            <input class="field" type="text" name="amount">
                        </label>
                        <p>{% trans "Format: x.dd where x is 1 to 10 numerals." %}</p>

                        <input class="button" type="submit" value={% trans "Submit" %}>
                    </form>
                </div>

    		</div>

		</div>

	</body>

</html>

templates/browse.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 //EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>

	<head>

		<title>Auctioneer - {{ title }}</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link href="{% static "style_main.css"%}" rel="stylesheet" type="text/css">

	</head>

	<body>

		<div id=Container>

			<div id=PrimaryMenu>
				<h1>Auctioneer - {{ title }}</h1>
			</div>

            {% include "links.html" %}

			<div id=TopPatch>
				<!-- Patch element at top of the page -->
			</div>

			<div id=Content>

                <div>
                    <form action="/auctioneer/auctions/" method="post">
                        {% csrf_token %}
                        <label>
                            <input class="field" type="text" name="query">
                        </label>
                        <input type="submit" class="button" value={% trans "Search" %}>
                    </form>
                </div>

                {% if is_search %}
                <div>
                    <h3>{% trans "Results for:" %}</h3>
                    <p>{{ query }}</p>
                </div>
                {% endif %}

                {% for content in content_list %}
                <div>
				    <h3>{{ content.title }}{% if content.banned %} {% trans "[BANNED]" %}{% endif %}{% if content.resolved %} {% trans "[RESOLVED]" %}{% endif %}</h3>
                    <p>{% trans "Created by:" %}Created by: {{ content.seller }}</p>
                    {% with content.bids_set.all|first as bid %}
                    {% if bid %}
                    <p>{% trans "Current price:" %} {{ bid.amount }} EUR</p>
                    {% else %}
                    <p>{% trans "Current price:" %} {{ content.startingPrice }} EUR</p>
                    {% endif %}
                    {% endwith %}
                    <p>{% trans "Start date:" %} {{ content.startDate }}</p>
                    <p>{% trans "Deadline:" %} {{ content.stopDate }}</p>
                    <form action="/auctioneer/auctions/{{ content.id }}" method="get">
                        <input type="submit" class="button" value={% trans "Details" %}>
                    </form>
                </div>
                {% empty %}
                <div>
                    <h3>{% trans "No content!" %}</h3>
                </div>
                {% endfor %}

			</div>

		</div>

	</body>

</html>

templates/confirm.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 //EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>

	<head>

		<title>Auctioneer - {{ title }}</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link href="{% static "style_main.css"%}" rel="stylesheet" type="text/css">

	</head>

	<body>

		<div id=Container>

			<div id=PrimaryMenu>
				<h1>Auctioneer - {{ title }}</h1>
			</div>

            {% include "links.html" %}

			<div id=TopPatch>
				<!-- Patch element at top of the page -->
			</div>

			<div id=Content>

                <div>
                    <h3>{% trans "Confirm auction:" %}</h3>
                    <p>{% trans "Title:" %} {{ auction_title }}</p>
                    <p>{% trans "Description:" %} {{ description }}</p>
                    <p>{% trans "Starting price:" %} {{ starting_price }}</p>
                    <p>{% trans "Starting date:" %} {{ start }}</p>
                    <p>{% trans "Deadline:" %} {{ stop }}</p>
                </div>

                <div>
                    <h3>{% trans "Confirm auction?" %}</h3>
                    <form action="/auctioneer/auctions/confirm/" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="status" value="True">
                        <input type="submit" class="button" value={% trans "Yes" %}>
                    </form>
                    <form action="/auctioneer/auctions/confirm/" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="status" value={% trans "No" %}>
                        <input type="submit" class="button" value="No">
                    </form>
                </div>

			</div>

		</div>

	</body>

</html>

templates/create.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 //EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>

	<head>

		<title>Auctioneer - {{ title }}</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link href="{% static "style_main.css"%}" rel="stylesheet" type="text/css">

	</head>

	<body>

		<div id=Container>

			<div id=PrimaryMenu>
				<h1>Auctioneer - {{ title }}</h1>
			</div>

            {% include "links.html" %}

			<div id=TopPatch>
				<!-- Patch element at top of the page -->
			</div>

			<div id=Content>

                <div>
                    <h3>{% trans "Create Auction" %}</h3>
                </div>

                {% if message %}
                <div>
                    <h3>{{ message }}</h3>
                </div>
                {% endif %}

                <div>
                    <form action="/auctioneer/auctions/create/" method="post">
                        {% csrf_token %}
                        <label>
                            <span>{% trans "Title" %}</span>
                            <input class="field" type="text" name="title">
                        </label>
                        <label>
                            <span>{% trans "Description" %}</span>
                            <textarea rows="5" cols="30" name="description"></textarea>
                        </label>
                        <label>
                            <span>{% trans "Starting price" %}</span>
                            <input class="field" type="text" name="starting_price">
                        </label>
                        <label>
                            <span>{% trans "Start date (YYYY-MM-DD hh:mm or 'now')" %}</span>
                            <input class="field" type="text" name="start">
                        </label>
                        <label>
                            <span>{% trans "Deadline (YYYY-MM-DD hh:mm)" %}</span>
                            <input class="field" type="text" name="stop">
                        </label>
                        <p>{% trans "NOTE: Minimum duration is 3 days (72h)" %}</p>
                        <input type="submit" class="button" value={% trans "Create" %}>
                    </form>
                </div>

			</div>

		</div>

	</body>

</html>

templates/create_auction.html
{% load staticfiles %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 //EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>

	<head>

		<title>Auctioneer - {{ title }}</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link href="{% static "style_main.css"%}" rel="stylesheet" type="text/css">

	</head>

	<body>

		<div id=Container>

			<div id=PrimaryMenu>
				<h1>Auctioneer - {{ title }}</h1>
			</div>

            {% include "links.html" %}

			<div id=TopPatch>
				<!-- Patch element at top of the page -->
			</div>

			<div id=Content>

                <div>
                    <form action="/auctioneer/auction/create/" method="post">
                        <label>
                            <span>Label</span>
                            <input type="text" name="input">
                        </label>
                        <label>
                            <span>Label</span>
                            <textarea rows="10" cols="30"></textarea>
                        </label>
                        <label>
                            <span>Label</span>
                            <input type="submit" name="save" value="Save">
                        </label>
                    </form>
                </div>

			</div>

		</div>

	</body>

</html>

templates/details.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 //EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>

	<head>
	
		<title>Auctioneer - {{ title }}</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link href="{% static "style_main.css"%}" rel="stylesheet" type="text/css">
		
	</head>

	<body>	
	
		<div id=Container>
		
			<div id=PrimaryMenu>
				<h1>Auctioneer - {{ title }}</h1>
			</div>
			
            {% include "links.html" %}
			
			<div id=TopPatch>
				<!-- Patch element at top of the page -->			
			</div>
		
			<div id=Content>

                {% with content as auction %}
                <div>
                    <h3>{{ auction.title }}{% if auction.banned %} {% trans "[BANNED]" %}{% endif %}{% if auction.resolved %} {% trans "[RESOLVED]" %}{% endif %}</h3>
                    <p>{% trans "Created by:" %} {{ auction.seller }}</p>
                    <p>{% trans "Deadline:" %} {{ auction.stopDate }}</p>
                    <p>{% trans "Description:" %} {{ auction.description }}</p>
                    {% with auction.bids_set.all|first as top %}
                    {% if top %}
                    <h3>{% trans "Current price:" %} {{ top.amount }} EUR</h3>
                    <p>{% trans "by:" %} {{ top.bidder }}</p>
                    <p>@ {{ top.timestamp }}</p>
                    {% else %}
                    <h3>{% trans "Current price:" %} {{ auction.startingPrice }} EUR</h3>
                    {% endif %}
                    {% endwith %}
                    {% if not seller %}
                    {% if not auction.resolved %}
                    <form action="/auctioneer/auctions/{{ auction.id }}/bid/" method="get">
                        <input type="submit" class="button" value={% trans "Bid" %}>
                    </form>
                    {% endif %}
                    {% else %}
                    <form action="/auctioneer/auctions/{{ auction.id }}/edit/" method="get">
                        <input type="submit" class="button" value={% trans "Edit" %}>
                    </form>
                    {% endif %}
                    {% if admin %}
                    <form action="/auctioneer/auctions/{{ auction.id }}/ban/" method="get">
                        <input type="submit" class="button" value={% trans "Ban" %}>
                    </form>
                    {% endif %}
                </div>

                {% for bid in auction.bids_set.all %}
                <div>
                    <h3>{% trans "Bid:" %} {{ bid.amount }} EUR</h3>
                    <p>{% trans "by:" %} {{ bid.bidder }}</p>
                    <p>@ {{ bid.timestamp }}</p>
                </div>
                {% empty %}
                <div>
                    <h3>{% trans "No bids!" %}</h3>
                </div>
                {% endfor %}
                {% endwith %}

    		</div>
			
		</div>
		
	</body>

</html>

templates/edit.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 //EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>

	<head>

		<title>Auctioneer - {{ title }}</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link href="{% static "style_main.css"%}" rel="stylesheet" type="text/css">

	</head>

	<body>

		<div id=Container>

			<div id=PrimaryMenu>
				<h1>Auctioneer - {{ title }}</h1>
			</div>

            {% include "links.html" %}

			<div id=TopPatch>
				<!-- Patch element at top of the page -->
			</div>

			<div id=Content>

                <div>
                    <h3>{% trans "Edit Auction" %}</h3>
                </div>

                <div>
                    <form action="/auctioneer/auctions/{{ auction.id }}/edit/" method="post">
                        {% csrf_token %}
                        <label>
                            <span>{% trans "Title" %}</span>
                            <p>{{ auction.title }}</p>
                        </label>
                        <label>
                            <span>{% trans "Description" %}</span>
                            <textarea rows="5" cols="30" name="description">{{ auction.description }}</textarea>
                        </label>
                        <label>
                            <span>{% trans "Starting price" %}</span>
                            <p>{{ auction.startingPrice }} EUR</p>
                        </label>
                        <label>
                            <span>{% trans "Start date" %}</span>
                            <p>{{ auction.startDate }}</p>
                        </label>
                        <label>
                            <span>{% trans "Deadline" %}</span>
                            <p>{{ auction.stopDate }}</p>
                        </label>
                        <input type="submit" class="button" value={% trans "Save" %}>
                    </form>
                </div>

			</div>

		</div>

	</body>

</html>

templates/language.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 //EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>

	<head>

		<title>Auctioneer - {{ title }}</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link href="{% static "style_main.css"%}" rel="stylesheet" type="text/css">

	</head>

	<body>

		<div id=Container>

			<div id=PrimaryMenu>
				<h1>Auctioneer - {{ title }}</h1>
			</div>

            {% include "links.html" %}

			<div id=TopPatch>
				<!-- Patch element at top of the page -->
			</div>

			<div id=Content>

                <div>
                    <h3>{% trans "Language" %}</h3>
                    <form action="/auctioneer/language/" method="post">
                        {% csrf_token %}
                        <label>
                            <select name="language" size="2">
                            {% if language == 'sv' %}
                            <option value="en">{% trans "English" %}</option>
                            <option value="sv" selected>{% trans "Swedish" %}</option>
                            {% else %}
                            <option value="en" selected>{% trans "English" %}</option>
                            <option value="sv">{% trans "Swedish" %}</option>
                            {% endif %}
                            </select>
                        </label>
                        <br><br>
                        <label>
                            <input class="button" type="submit" size="30" value={% trans "Save" %}>
                        </label>
                    </form>
                </div>

			</div>

		</div>

	</body>

</html>

templates/links.html
{% load i18n %}
<div id=SecondaryMenu>
    <div><h4><a href='/auctioneer/home/'>{% trans "Home" %}</a></h4></div>
    <div><h4><a href='/auctioneer/auctions/'>{% trans "Browse" %}</a></h4></div>
    <div><h4><a href='/auctioneer/language/'>{% trans "Language" %}</a></h4></div>

{% if is_logged_in %}
    <div><h4><a href='/auctioneer/account/auctions/'>{% trans "My Auctions" %}</a></h4></div>
    <div><h4><a href='/auctioneer/auctions/create/'>{% trans "Create" %}</a></h4></div>
    <div><h4><a href='/auctioneer/account/'>{% trans "Account" %}</a></h4></div>
    <div><h4><a href='/auctioneer/logout/'>{% trans "Logout" %}</a></h4></div>
{% else %}
    <div><h4><a href='/auctioneer/signup/'>{% trans "Sign Up" %}</a></h4></div>
    <div><h4><a href='/auctioneer/login/'>{% trans "Login" %}</a></h4></div>
{% endif %}
</div>

templates/main.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 //EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>

	<head>
	
		<title>Auctioneer - {{ title }}</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link href="{% static "style_main.css"%}" rel="stylesheet" type="text/css">
		
	</head>

	<body>	
	
		<div id=Container>
		
			<div id=PrimaryMenu>
				<h1>Auctioneer - {{ title }}</h1>
			</div>
			
            {% include "links.html" %}
			
			<div id=TopPatch>
				<!-- Patch element at top of the page -->			
			</div>
		
			<div id=Content>

                <div>
                    <h3>{{ tag }}</h3>
                </div>

                {% for content in content_list %}
                <div>
				    <h3>{{ content.title }}{% if content.banned %} {% trans "[BANNED]" %}{% endif %}{% if content.resolved %} {% trans "[RESOLVED]" %}{% endif %}</h3>
                    <p>{% trans "Created by:" %} {{ content.seller }}</p>
                    {% with content.bids_set.all|first as bid %}
                    {% if bid %}
                    <p>{% trans "Current price:" %} {{ bid.amount }} EUR</p>
                    {% else %}
                    <p>{% trans "Current price:" %} {{ content.startingPrice }} EUR</p>
                    {% endif %}
                    {% endwith %}
                    <p>{% trans "Start date:" %} {{ content.startDate }}</p>
                    <p>{% trans "Deadline:" %} {{ content.stopDate }}</p>
                    <form action="/auctioneer/auctions/{{ content.id }}" method="get">
                        <input type="submit" class="button" value={% trans "Details" %}>
                    </form>
                </div>
                {% empty %}
                <div>
                    <h3>{% trans "No content!" %}</h3>
                </div>
                {% endfor %}

			</div>
			
		</div>
		
	</body>

</html>

templates/message.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 //EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>

	<head>

		<title>Auctioneer - {{ title }}</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link href="{% static "style_main.css"%}" rel="stylesheet" type="text/css">

	</head>

	<body>

		<div id=Container>

			<div id=PrimaryMenu>
				<h1>Auctioneer - {{ title }}</h1>
			</div>

            {% include "links.html" %}

			<div id=TopPatch>
				<!-- Patch element at top of the page -->
			</div>

			<div id=Content>

                <div><h3>{{ message }}</h3></div>

			</div>

		</div>

	</body>

</html>

templates/signup.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 //EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>

	<head>

		<title>Auctioneer - {{ title }}</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link href="{% static "style_main.css"%}" rel="stylesheet" type="text/css">

	</head>

	<body>

		<div id=Container>

			<div id=PrimaryMenu>
				<h1>Auctioneer - {{ title }}</h1>
			</div>

            {% include "links.html" %}

			<div id=TopPatch>
				<!-- Patch element at top of the page -->
			</div>

			<div id=Content>

                <div>
                    <form action="/auctioneer/signup/" method="post">
                        {% csrf_token %}
                        <label>
                            <span>{% trans "E-Mail" %}</span>
                            <input class="field" type="text" size="30" name="email">
                        </label>
                        <label>
                            <span>{% trans "Username" %}</span>
                            <input class="field" type="text" size="30" name="username">
                        </label>
                        <label>
                            <span>{% trans "Password" %}</span>
                            <input class="field" type="password" size="30" name="password">
                        </label>
                        <br>
                        <label>
                            <input class="button" type="submit" size="30" value={% trans "Create" %}>
                        </label>
                    </form>
                </div>

			</div>

		</div>

	</body>

</html>